from repESP.types import *
from repESP.resp_util import _Respin, _parse_respin, _write_respin

from my_unittest import TestCase

from io import StringIO


class TestRespin(TestCase):

    def setUp(self) -> None:

        self.respin = _Respin(
            title="RESP input of type '2' generated by the repESP program",
            cntrl=_Respin.Cntrl(
                nmol=1,
                ihfree=1,
                ioutopt=1,
                qwt=0.001,
                iqopt=2
            ),
            wtmol=1.0,
            subtitle="Resp charges for organic molecule",
            charge=0,
            iuniq=5,
            atomic_numbers=[6, 1, 1, 1, 1],
            ivary_numbers=[0, 0, 2, 2, 2]
        )


    def test_parsing(self) -> None:
        with open("tests/test_resp_util.respin") as f:
            parsed_respin = _parse_respin(f)
        self.assertAlmostEqualRecursive(self.respin, parsed_respin)

    def test_writing(self) -> None:
        written = StringIO()
        _write_respin(written, self.respin)
        written.seek(0)

        with open("tests/test_resp_util.respin") as f:
            self.assertListEqual(f.readlines(), written.readlines())
