import argparse

parser = argparse.ArgumentParser(add_help=False)

parser.add_argument("--respin_location",
                    help="""The directory with the location of the *two* respin
                    files. Their names are expected to end with '.respin1' and
                    '.respin2'. They can be generated using the 'respgen'
                    program (see 'instructions.md').""",
                    default='.', metavar="RESPIN_LOCATION")

esp_file_help = """The name of the 'esp' file with ESP fitting points.
    This file must be in the same directory as the 'respin' files. The file can
    be generated by running a Gaussian Pop calculation with IOp(6/50)=1."""
